In [31]:
# Subtype 	 Type 	 Date 	 Date 	 Sequence 	 Cashier Name 	 Custom Data 	 USD Amount 

# END_OF_SHIFT = SUM by DATE( USD Amount , Type = "END_OF_SHIFT")+ SUM by DATE (USD AMOUNT, Type = "DEPOSIT", subtype is "" (blank))
# Tills Pulled = SUM by DATE( all BLANK "" subtype, type = DISPENSE) - SUBTRACT (DISPENSE with no custom data (Need User Input))
# Total Cash Sales = End of Shift + Tills

In [32]:
#imports
import pandas as pd
import numpy as np

In [61]:
cash_recon = pd.read_excel("May 22 Raw Cash Treez Data.xlsx",[0,1])
raw_data = cash_recon[0][["Subtype", "Type", "Datetime", "Sequence", "Cashier Name", "Custom Data", "USD Amount"]].copy()
raw_data["Date"] = pd.to_datetime(raw_data["Datetime"])
cashierlist = ["Ballesteros, Michael","MCGEE, MIKE","Hernandez, Melissa","SERENO, CLAUDIA", "SANDERS, ERNIE", "TUCCI, NICK"]

recon = pd.DataFrame(pd.Series(raw_data["Date"].dt.date.unique(),name="Date")).set_index("Date")

# raw_data.fillna(0)

recon["End of Shift"] = 0
recon["Tills Pulled"] = 0
for index, row in raw_data.iterrows():
#     print(row["Cashier Name"])
    prev = recon.loc[recon.index[row["Date"].day-1], "End of Shift"]
    dollars = [0 if np.isnan(row["USD Amount"]) else float(row["USD Amount"])][0]
#     print(dollars)

    #End of Shift calculation
    if row["Type"]=="END_OF_SHIFT":
        recon.loc[recon.index[row["Date"].day-1], "End of Shift"] = float(prev) + dollars
    if row["Type"]=="DEPOSIT" and not isinstance(row["Subtype"], str):
        recon.loc[recon.index[row["Date"].day-1], "End of Shift"] = float(prev) + dollars
    
    prev = recon.loc[recon.index[row["Date"].day-1], "Tills Pulled"]
    USDList = [-400, -174, -225]
    #Tills Pulled calculation
    if row["Type"]=="DISPENSE" and not isinstance(row["Subtype"], str):
        if not(row["Custom Data"]=="{}" and row["Cashier Name"] in cashierlist):
            recon.loc[recon.index[row["Date"].day-1], "Tills Pulled"] = float(prev) + dollars
        else:
            if row["Cashier Name"] == "SERENO, CLAUDIA" and row["USD Amount"] in USDList:
                recon.loc[recon.index[row["Date"].day-1], "Tills Pulled"] = float(prev) + dollars
display(recon)
# raw_data.to_csv("May 2022 CashReconScript Export.csv")

c:\python39\lib\site-packages\dateutil\parser\_parser.py:1207: UnknownTimezoneWarning: tzname PDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

            End of Shift  Tills Pulled
Date
2022-05-01      54000.18      -6565.00
2022-05-02      57151.65      -7780.00
2022-05-03      56106.17      -6565.00
2022-05-04      55071.10      -5765.00
2022-05-05      60924.46      -5750.00
2022-05-06      77089.53      -6965.00
2022-05-07      59054.87      -6335.00
2022-05-08      58952.96      -6175.00
2022-05-09      54869.72      -6165.00
2022-05-10      53471.07      -6983.00
2022-05-11      56081.20      -6379.95
2022-05-13      69083.70      -7450.00
2022-05-12      92789.38      -8135.00
2022-05-14      62850.44      -7850.00
2022-05-15      56580.65      -6310.00
2022-05-16      55425.33      -6250.00
2022-05-17      55238.33      -7850.00
2022-05-18      45480.21      -6665.00
2022-05-19      58571.73      -6655.00
2022-05-20      72579.45      -7090.00
2022-05-21      65687.39      -7049.00
2022-05-22      56550.56      -6665.00
2022-05-23      49536.80      -6245.75
2022-05-24      54477.42      -7541.84
2022-05-25      57287.64      -6661.08
2022-05-26      63574.50      -6995.00
2022-05-27      70832.76      -7487.85
2022-05-28      63501.53      -7465.00
2022-05-29      61169.05      -6895.00
2022-05-30      50729.73      -6550.00
2022-05-31      49654.86      -6250.00